#! /bin/bash


cd pack/ak_editor/opt/telescope-fzf-native.nvim
make

cd -

cd pack/ak_treesitter/opt/nvim-treesitter
#  :TSUpdate

cd -

cd pack/ak_lang/opt/mason.nvim
# :MasonUpdate

cd -

cd pack/ak_lang/opt/markdown-preview.nvim
# vim.fn["mkdp#util#install"]()

cd -

cd pack/ak_lang/opt/peek.nvim
deno task --quiet build:fast
