#! /bin/bash

function fzf() {
	echo "--> Start -make- telescope-fzf-native"
	cd pack/editor_ak/opt/telescope-fzf-native.nvim
	make
	cd -
}

function luasnip() {
	echo "--> Start -make- luasnip"
	cd pack/coding_ak/opt/LuaSnip
	make install_jsregexp
	cd -
}

function peek() {
	echo "--> Start deno task for peek.nvim"
	cd pack/lang_ak/opt/peek.nvim
	deno task --quiet build:fast
	cd -
}

function mkdp() {
	echo "--> Start mkdp#util#install for markdown-preview"
	nvim --headless -u NONE +"packadd markdown-preview.nvim" +"call mkdp#util#install_sync(v:true)" +qa
}

fzf
luasnip
peek
mkdp

echo "--> All done...:"
echo "Open neovim without arguments. Mason and treesitter will update automatically"
echo " "
echo "Don't forget: helptags ALL"
echo "Don't forget on update: treesitter :TSUpdate, mason :MasonUpdate"
echo "python-semshi :UpdateRemotePlugins"
